### ISSUE TITLE
"make demo" failed with file missing

### ISSUE THREAD

**Issue by pedia** [youtube/spfjs#461]
Trace detail:
```shell
> ninja demo && cd build/demo && python -m app

[68/68] symlink ../../src/server/demo/app.py -> build/demo/app.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/mordo/res/spfjs/build/demo/app.py", line 17, in <module>
    import web  # pylint: disable=import-error
  File "/Users/mordo/res/spfjs/build/demo/web/__init__.py", line 14, in <module>
    import utils, db, net, wsgi, http, webapi, httpserver, debugerror
ModuleNotFoundError: No module named 'utils'
```

ps: Is this project discontinued?

**Comment by pedia** [comment]
wowo, This project only worked under Python2
